# Generated by Django 5.0.6 on 2024-07-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0003_employee_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_Id',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='user_Id',
        ),
    ]
