# Generated by Django 5.0.6 on 2024-07-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0004_remove_employee_user_id_remove_jobseeker_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='drinking',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Socialy'), ('O', 'Occasionally'), ('T', 'Teetotaler'), ('P', 'Plan to Quit')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='fath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_tonge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rel_status',
            field=models.CharField(choices=[('S', 'Single'), ('SK', 'Single with Kid(s)'), ('D', 'Divorced'), ('DK', 'Divorced with Kid(s)'), ('W', 'Widowed'), ('WK', 'Widowed with Kid(s)'), ('SP', 'Separated'), ('SPK', 'Separated with Kid(s)')], default='S', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('P', 'Plan to Quit')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
