# Generated by Django 5.0.6 on 2024-07-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0005_user_bio_user_community_user_dob_user_drinking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
    ]
