# Generated by Django 5.0.6 on 2024-07-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0006_remove_emailotp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Jobseeker',
        ),
    ]
