# Generated by Django 5.0.6 on 2024-07-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0009_longrelationship_shortrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='community',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fath',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_tonge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
    ]
