# Generated by Django 5.0.6 on 2024-07-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0010_remove_user_community_remove_user_fath_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
