# Generated by Django 5.0.6 on 2024-07-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learntestapp', '0012_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
    ]
